# Generated by Django 4.1.7 on 2023-03-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_about_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img_url',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='skill',
            name='img_url',
            field=models.CharField(max_length=4000),
        ),
    ]
